version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
    timezone: "America/Sao_Paulo"
  open-pull-requests-limit: 10
  reviewers:
  - tomaslm
  allow:
  - dependency-type: direct
  - dependency-type: indirect